# Generated by Django 4.0 on 2022-01-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name="Bo'limlar nomi")),
                ('description', models.TextField(max_length=500, verbose_name="bo'lim  izohi")),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='user-img.png', null=True, upload_to='user_pic/', verbose_name='Foydalanuvchi rasmi')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='yaratilgan vaqti')),
                ('interesting', models.CharField(max_length=200, null=True, verbose_name='qiziqishlari')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Asar nomi')),
                ('author_name', models.CharField(max_length=200, verbose_name='Muallaif  nomi')),
                ('description', models.TextField(max_length=500, verbose_name='Asar syujeti ')),
                ('book_heroes', models.TextField(max_length=500, verbose_name='Asar qahramonlari ')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('comment', models.TextField(max_length=500, verbose_name='Asar hadida fikringiz')),
                ('complete', models.BooleanField(default=False, null=True, verbose_name="O'qilgan/O'qilmagan")),
                ('image', models.ImageField(upload_to='book/', verbose_name='rasm')),
                ('file', models.FileField(upload_to='book_pdf', verbose_name='PDFfayl')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name="Bo'lim nomi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
